StuSys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import ScoreMgr.urls
import UserMgr.urls
from StuSys import settings

admin.autodiscover()

urlpatterns = [
    url(r'^$', 'StuSys.views.Index', name='homeindex'),
    url(r'^adminsite/', admin.site.urls),
    url(r'^accounts/',include(UserMgr.urls)),
    url(r'^score/',include(ScoreMgr.urls)),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATICFILES_DIRS[0],}),
]

UserMgr/urls.py
from django.conf.urls import patterns, include, url

import UserMgr.views

urlpatterns = patterns('UserMgr.views',
    url(r'^login/$', 'LoginUser', name='loginurl'),
    url(r'^logout/$', 'LogoutUser', name='logouturl'),
    url(r'^ucinfo/$', 'UserInfoShow', name='ucinfo'),
    url(r'^admin/list/$', 'ListUser', name='uclist'),
    url(r'^admin/add/$', 'AddUser', name='ucadd'),
    url(r'^changepassword/$', 'ChangePassword', name='changepassword'),
    url(r'^admin/edit/(?P<ID>\d+)/$', 'EditUser', name='ucedit'),
    url(r'^admin/del/(?P<ID>\d+)/$', 'DelUser', name='ucdel'),
    url(r'^admin/class/add/$', 'AddClass', name='addclass'),
    url(r'^admin/class/list/$', 'ClassMgrList', name='listclass'),
    url(r'^admin/class/edit/(?P<ID>\d+)/$', 'EditClass', name='editclass'),
    url(r'^admin/class/del/(?P<ID>\d+)/$', 'DelClass', name='delclass'),
)

UserMgr/models.py
#-*- coding:utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import BaseUserManager,AbstractBaseUser
from django.contrib.auth.hashers import make_password
from django.db import models
import datetime

SEX_CHOICES = [
    (u'0', u'男'),
    (u'1', u'女'),
]

ROLE_CHOICES = [
    (0, u'学生'),
    (1, u'老师'),
    (2, u'管理员'),
]

class UserManager(BaseUserManager):
    def create_user(self,username,password=None):
        user=self.model(
            username=username,
        )

        user.role=0
        user.set_password(password)
        user.last_login = datetime.datetime.now()
        user.save(using=self._db)
        return user

    def create_superuser(self,username,password):
        user=self.model(
            username=username,
        )

        user.role=2
        user.set_password(password)
        user.last_login=datetime.datetime.now()
        user.save(using=self._db)
        return user


# Create your models here.

class Class(models.Model):
    classid   = models.CharField(u'班号', unique=True, max_length=16)
    classname = models.CharField(u"班级名称", max_length=20)
    def __unicode__(self):
        return self.classid
    class Meta:
        db_table = u'ClassInfo'         # 创建数据库的时候名字叫做ClassInfo
        verbose_name_plural=u'班级'

class Course(models.Model):
    begindate = models.DateField(u'开始日期')
    enddate   = models.DateField(u'结束日期')
    term      = models.CharField(u'学期',max_length=16)
    name      = models.CharField(u'名字',max_length=16,unique=True)
    def __unicode__(self):
        return self.name
    class Meta:
        db_table = u'CourseInfo'
        verbose_name_plural = u'专业课程'

class Person(AbstractBaseUser):
    # user = models.OneToOneField(User)
    username = models.CharField(max_length=40, unique=True, db_index=True)
    # password = models.TextField()
    role     = models.IntegerField(choices=ROLE_CHOICES)
    realname = models.CharField(u'姓名', max_length=16)
    theclass = models.ForeignKey(Class, verbose_name=u'班级', null=True, blank=True)
    sex      = models.CharField(u'性别', choices=SEX_CHOICES, max_length=1)
    course   = models.ManyToManyField(Course, null=True, blank=True)

    USERNAME_FIELD = 'username' # 定义auth模块使用的用户名字段
    objects = UserManager()     # 定义用户管理器
    def __unicode__(self):
        return self.realname
    class Meta:
        db_table = u'Person'

class Score(models.Model):
    course    = models.ForeignKey(Course)
    student   = models.ForeignKey(Person)
    score     = models.IntegerField()

UserMgr/views.py
# coding=utf-8
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.contrib import auth
from django.template import RequestContext
from django.contrib import messages
from UserMgr.form import LoginUserForm, ChangePasswordForm, AddUserForm, ClassForm
from UserMgr.models import Class, Person
from django.contrib.auth import get_user_model


# Create your views here.

# user操作

def LoginUser(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')

    if request.method == 'GET' and request.GET.has_key('next'):
        next = request.GET['next']
    else:
        next = '/'

    if next.find('logout') > -1:
        next = '/'

    if request.method == "POST":
        form = LoginUserForm(request, data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            messages.success(request,u"登陆成功")
            return HttpResponseRedirect(request.POST['next'])
    else:
        form = LoginUserForm(request)

    kwvars = {
        'request':request,
        'form':form,
        'next':next,
    }

    return render_to_response('login.html',kwvars,RequestContext(request))


@login_required
def LogoutUser(request):
    auth.logout(request)
    kwvars = {
        'request':request,
    }
    return render_to_response('logged_out.html',kwvars, RequestContext(request))


@login_required
def UserInfoShow(request):
    return render_to_response('user.info.html', {}, RequestContext(request))


@login_required
def ChangePassword(request):
    if request.method=='POST':
        form = ChangePasswordForm(user=request.user,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('logouturl'))
    else:
        form = ChangePasswordForm(user=request.user)

    kwvars = {
        'form':form,
        'request':request,
    }

    return render_to_response('password.change.html',kwvars,RequestContext(request))


@login_required
def ListUser(request):
    if not request.user.role == 2:
        messages.error(request,u"权限不足！")
        return HttpResponseRedirect("/")
    UserList = get_user_model().objects.all()
    kwvars = {
        'request': request,
        'UserList':UserList,
    }
    return render_to_response('user.list.html', kwvars, RequestContext(request))


@login_required
def AddUser(request):
    if not request.user.role == 2:
        messages.error(request,u"权限不足！")
        return HttpResponseRedirect("/")
    if request.method == "POST":
        form = AddUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,u"添加用户成功")
            return HttpResponseRedirect(reverse('uclist'))
    else:
        form = AddUserForm()

    kwvars = {
        'form': form,
        'title':u"添加用户",
    }

    return render_to_response('common/common.form.html', kwvars, RequestContext(request))


@login_required
def EditUser(request, ID):
    if not request.user.role == 2:
        messages.error(request,u"权限不足！")
        return HttpResponseRedirect("/")

    try:
        users = Person.objects.get(id=ID)
    except Person.DoesNotExist:
        messages.error(request, u'<b>编辑人员失败</b><br /><b>详细信息：</b>找不到ID为%s的人员！'%ID)
        return HttpResponseRedirect("/")
    if request.method == "POST":
        form = AddUserForm(request.POST, instance=users)
        if form.is_valid():
            form.save()
            messages.success(request,u"修改人员成功")
            return HttpResponseRedirect(reverse('uclist'))
    else:
        form = AddUserForm(instance=users)

    kwvars = {
        'form': form,
        'title':u"修改人员",
    }

    return render_to_response('common/common.form.html', kwvars, RequestContext(request))


@login_required
def DelUser(request, ID):
    if not request.user.role == 2:
        messages.error(request,u"权限不足！")
        return HttpResponseRedirect("/")

    try:
        Person.objects.get(id=ID).delete()
        messages.success(request, u"删除人员成功")
        return HttpResponseRedirect(reverse('uclist'))
    except Person.DoesNotExist:
        messages.error(request, u'<b>删除人员失败</b><br /><b>详细信息：</b>找不到ID为%s的人员！'%ID)
        return HttpResponseRedirect(reverse('uclist'))

# class操作


@login_required
def ClassMgrList(request):
    if not request.user.role == 2:
        messages.error(request,u"权限不足！")
        return HttpResponseRedirect("/")
    ClassList = Class.objects.all()
    kwvars = {
        'request': request,
        'ClassList':ClassList,
    }
    return render_to_response('class.mgr.list.html', kwvars, RequestContext(request))

def AddClass(request):
    if not request.user.role == 2:
        messages.error(request,u"权限不足！")
        return HttpResponseRedirect("/")
    if request.method == "POST":
        form = ClassForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,u"添加班级成功")
            return HttpResponseRedirect(reverse('listclass'))
    else:
        form = ClassForm()

    kwvars = {
        'form': form,
        'title':u"添加班级",
    }

    return render_to_response('common/common.form.html', kwvars, RequestContext(request))


@login_required
def EditClass(request, ID):
    if not request.user.role == 2:
        messages.error(request,u"权限不足！")
        return HttpResponseRedirect("/")

    try:
        classes = Class.objects.get(id=ID)
    except Class.DoesNotExist:
        messages.error(request, u'<b>编辑课程失败</b><br /><b>详细信息：</b>找不到ID为%s的课程！'%ID)
        return HttpResponseRedirect("/")
    if request.method == "POST":
        form = ClassForm(request.POST, instance=classes)
        if form.is_valid():
            form.save()
            messages.success(request,u"修改课程成功")
            return HttpResponseRedirect(reverse('listclass'))
    else:
        form = ClassForm(instance=classes)

    kwvars = {
        'form': form,
        'title':u"修改课程",
    }

    return render_to_response('common/common.form.html', kwvars, RequestContext(request))

@login_required
def DelClass(request, ID):
    if not request.user.role == 2:
        messages.error(request,u"权限不足！")
        return HttpResponseRedirect("/")

    try:
        Class.objects.get(id=ID).delete()
        messages.success(request, u"删除课程成功")
        return HttpResponseRedirect(reverse('listclass'))
    except Class.DoesNotExist:
        messages.error(request, u'<b>删除课程失败</b><br /><b>详细信息：</b>找不到ID为%s的课程！'%ID)
        return HttpResponseRedirect(reverse('listclass'))

UserMgr/templates/addcourse.html
{% extends "base_site.html" %}

{% block content %}
    <div id="add-course-dialog">
        <form id="add-course-form" method="post" class="mws-form" action='{% url 'addcourse' %}'>
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="提交">
        </form>
    </div>
{% endblock %}

UserMgr/templates/base_site.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/bootstrap-duallistbox.css" rel="stylesheet">
    <script type="text/javascript" src="/static/js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/js/jquery.bootstrap-duallistbox.js"></script>
    <script type="text/javascript" src="/static/js/echarts.simple.min.js"></script>
</head>

<body>
<header class="navbar navbar-inverse navbar-fixed-top bs-blog-nav" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle bs-blog-navbs-blog-nav" type="button" data-toggle="collapse"
                    data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">学生成绩管理系统</a>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse bs-blog-nav" role="navigation">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/" _target="_self">首页</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    {% if user.realname != "" %}
                        <li>
                            <a href="#">{{ user.realname }}</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="#">{{ user.username }}</a>
                        </li>
                    {% endif %}

                    <li>
                        <a href="{% url 'logouturl' %}">登出</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'loginurl' %}">登陆</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>
<div class="container" style="margin-top: 80px;">
    <div class="row">
        <div class="col-md-3">
            {% include 'common/sidebar.html' %}
        </div>
        <div class="col-md-9">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %}
                        class="alert alert-{{ message.tags }}"{% endif %}role="alert">{{ message|safe }}</div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
    </div>

</div>
</body>


</html>

UserMgr/templates/class.mgr.list.html
{% extends "base_site.html" %}

{% block content %}
<table class="table table-hover table-striped  table-bordered table-condensed">
    <tr>
        <th>#</th>
        <th>班级名称</th>
        <th>班级编号</th>
        <th>操作</th>
    </tr>

    {% for i in ClassList %}
        <tr style="font-size: 13px;">
            <td>{{ i.id }}</td>
            <td>{{ i.classname }}</td>
            <td>{{ i.classid }}</td>
            <td class="host_buttom">
                <a class="btn btn-warning btn-xs"  href="{% url 'editclass' i.id %}" >编辑</a>
                <a class="btn btn-danger btn-xs" href="{% url 'delclass' i.id %}" onclick="return confirm('是否确认删除？')">删除</a>
            </td>
        </tr>
    {% endfor %}

</table>
{% endblock %}

UserMgr/templates/index.html
{% extends "base_site.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>欢迎！</h1>
        <h2>您的身份是：{{ user.get_role_display }}</h2>
    </div>
{% endblock %}

UserMgr/templates/login.html
{% extends "base_site.html" %}

{% block content %}
    {% if form.errors and not form.non_field_errors %}
        <p class="errornote">
            "登陆失败！"
        </p>
    {% endif %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <p class="errornote">
                {{ error }}
            </p>
        {% endfor %}
    {% endif %}

    <div id="content-main" class="jumbotron">
        <div class="row">
        <div class="col-md-4 col-md-offset-4">
        <h1>登陆</h1>
    {% if user.is_authenticated %}
    <p class="errornote">
        您的权限不足。
    </p>
    {% endif %}

    <form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
      <div class="form-row">
        {{ form.username.errors }}
        {{ form.username.label_tag }} {{ form.username }}
      </div>
      <div class="form-row">
        {{ form.password.errors }}
        {{ form.password.label_tag }} {{ form.password }}
        <input type="hidden" name="next" value="{{ next }}" />
      </div>
      {% url 'admin_password_reset' as password_reset_url %}<p></p>
      <div class="submit-row">
        <label>&nbsp;</label><input type="submit" class="btn btn-primary btn-lg" value="登陆" />
      </div>
    </form>
        </div>
        </div>
    </div>

    <script type="text/javascript">
        $('#id_username').focus();
    </script>
{% endblock %}

UserMgr/templates/password_change_done.html
{% extends "base_site.html" %}
{% load i18n %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}
    <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} /
    <a href="{% url 'logouturl' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
        &rsaquo; {% trans 'Password change' %}
    </div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
    <p>{% trans 'Your password was changed.' %}</p>
{% endblock %}

UserMgr/templates/password_change_form.html
{% extends "base_site.html" %}
{% load i18n admin_static %}
{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %} {% trans 'Change password' %} / <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password change' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}<div id="content-main">

<form method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}


<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.old_password.errors }}
    {{ form.old_password.label_tag }} {{ form.old_password }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    {{ form.new_password1.label_tag }} {{ form.new_password1 }}
    {% if form.new_password1.help_text %}
    <p class="help">{{ form.new_password1.help_text|safe }}</p>
    {% endif %}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    {{ form.new_password2.label_tag }} {{ form.new_password2 }}
    {% if form.new_password2.help_text %}
    <p class="help">{{ form.new_password2.help_text|safe }}</p>
    {% endif %}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="{% trans 'Change my password' %}" class="default" />
</div>

<script type="text/javascript">document.getElementById("id_old_password").focus();</script>
</div>
</form></div>

{% endblock %}

UserMgr/templates/password_reset_complete.html
{% extends "base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

{% endblock %}

UserMgr/templates/password_reset_confirm.html
{% extends "base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset confirmation' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

{% if validlink %}

<p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form method="post">{% csrf_token %}
{{ form.new_password1.errors }}
<p class="aligned wide"><label for="id_new_password1">{% trans 'New password:' %}</label>{{ form.new_password1 }}</p>
{{ form.new_password2.errors }}
<p class="aligned wide"><label for="id_new_password2">{% trans 'Confirm password:' %}</label>{{ form.new_password2 }}</p>
<p><input type="submit" value="{% trans 'Change my password' %}" /></p>
</form>

{% else %}

<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

UserMgr/templates/password_reset_done.html
{% extends "base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

<p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>

{% endblock %}

UserMgr/templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
    {% blocktrans %}You're receiving this email because you requested a password reset for your user account at
        {{ site_name }}.{% endblocktrans %}

    {% trans "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}
    {% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

    {% trans "Thanks for using our site!" %}

    {% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

UserMgr/templates/password_reset_form.html
{% extends "base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>

<form method="post">{% csrf_token %}
{{ form.email.errors }}
<p><label for="id_email">{% trans 'Email address:' %}</label> {{ form.email }} <input type="submit" value="{% trans 'Reset my password' %}" /></p>
</form>

{% endblock %}

UserMgr/templates/user.info.html
{% extends "base_site.html" %}

{% block content %}

    <table class="table table-hover table-striped  table-bordered table-condensed">
        <tr>
            <th>用户名</th>
            <th>真实姓名</th>
            <th>角色</th>
            <th>最后登陆时间</th>
            <th>性别</th>
        </tr>

        <tr style="font-size: 13px;">
            <td>{{ user.username }}</td>
            <td>{{ user.realname }}</td>
            <td>{{ user.get_role_display }}</td>
            <td>{{ user.last_login|date:"Y-m-d H:i:s" }}</td>
            <td>{{ user.get_sex_display }}</td>
        </tr>

    </table>
{% endblock %}

UserMgr/templates/user.list.html
{% extends "base_site.html" %}

{% block content %}
<table class="table table-hover table-striped  table-bordered table-condensed">
    <tr>
        <th>#</th>
        <th>用户名</th>
        <th>真实姓名</th>
        <th>角色</th>
        <th>最后登陆时间</th>
        <th>性别</th>
        <th>操作</th>
    </tr>

    {% for i in UserList %}
        <tr style="font-size: 13px;">
            <td>{{ i.id }}</td>
            <td>{{ i.username }}</td>
            <td>{{ i.realname }}</td>
            <td>{{ i.get_role_display }}</td>
            <td>{{ i.last_login|date:"Y-m-d H:i:s" }}</td>
            <td>{{ i.get_sex_display }}</td>
            <td class="host_buttom">
                <a class="btn btn-warning btn-xs"  href="{% url 'ucedit' i.id %}" >编辑</a>
                <a class="btn btn-danger btn-xs" href="{% url 'ucdel' i.id %}" onclick="return confirm('是否确认删除？')">删除</a>
            </td>
        </tr>
    {% endfor %}

</table>
{% endblock %}